# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cu+V+E3oODD+WnOYnAN/a1Jz+9jh1MM6i8L1nUWFMSr/x2zA38fCfJRSDz3Tgxi0iF/UHqr6yEankCl03cuQBzsmWL3/+Pm+rJwFsp9n9KcfYg4aDTJjz8JeP/AF0xI3P01Fq7zwibD72eF3/33/mophGLINIflvQlRxe+LfxhUp9vuBvEx2cFaBKLI0hI12y9PFUVXPM4MCQuQr68AuVPto+66g95F8OcOLOJmrOtD/3MD3X7J79yuY0NGWeq4cKS8n3ye7AH+DbcEJMGpstiqvjEO6kRrsyv+m5KJrkF6MrTJoq/pMovm0gx4e+2NlfdSIiCYjbcQ5n/ckMbdZ5fQpv+Hnf7fjUGzQbpSL8hBJdfswvindoPLyetg+Bwn1c+O1GpGk2vFURxeq0xnU/qorlo6kTgcBQY63FsCs62ylHWdeiD063+9vnUwALW9hKFiOVVLW2aBDhUmc2VQ8TYtdvVEv+ZZExUBiG38sMt3Zz8bceSv+v7+qhTo6AOsuN1lhNBr1crR5YONqxLG7zA6JIuiB55YkgphFflIrt5/cidOjdlReyeLuQUwBi6LHnSqBW9bTdgjdNPxPr+7ePIBjlh+Zyf3E0nff+lSt79B+vC/S0uZEml/Mjaw/m17Z+nJAjlzSkznUGi/eGdxb1XeMPlTrtTF/p/E+xMAjLIQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
